#!/usr/bin/sh

# -proc:none to disable annotation processing.
# -7 for java 1.7 compatibility.
dalvikvm -Xmx256m \
         -Xcompiler-option --compiler-filter=speed \
         -cp ecj.jar \
         org.eclipse.jdt.internal.compiler.batch.Main \
         -proc:none \
         -7 \
         -cp android.jar \
         "$@"
